# Generated by Django 5.0.7 on 2024-08-01 08:15

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='take',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='booking',
            name='created',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 1, 8, 15, 29, 681104, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='take',
            name='timestamp',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
