# Generated by Django 5.0.7 on 2024-08-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_booking_options_alter_take_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created', 'updated']},
        ),
        migrations.AlterModelOptions(
            name='take',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='booking',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='take',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
