# Generated by Django 5.0.7 on 2024-08-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_alter_booking_options_alter_take_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
