# Generated by Django 5.0.7 on 2024-08-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='static/default.jpg', upload_to='images/'),
        ),
    ]
