# Generated by Django 5.0.7 on 2024-08-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_remove_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField(max_length=5000)),
            ],
        ),
    ]
